### PR TITLE
Fix issue with this plugin and 2.10

### LINKED ISSUE #131: Error with 2.10.3
Hi,

I get 

AttributeError: 'LdapPlugin' object has no attribute 'authenticate'

with ckan 2.10.3. Can one confirm that the plugin is working in this latest version?

Thanks,

– Toni

### PR DESCRIPTION
**Pull request by jrdh**
This "solves" an issue with running this plugin on 2.10 ckan where a method plugins implementing IAuthenticator was expected but wasn't provided by us (specifically `authenticate` which was added in 2.10.0). By inheriting the IAuthenticator base version we solve this problem for now, in that the plugin should work but it's still implemented in an old fashioned way and we should move to a more modern implementation.

The key change is here: https://github.com/NaturalHistoryMuseum/ckanext-ldap/commit/364cd809087e38d15c2800bd31add2a105367039, the other changes in this PR relate to detailing the CKAN 2.9 and 2.10 testing information in the readme.

I will test this on our staging site before merging, but both 2.9 and 2.10 tests pass with this change.

Closes #131

### CODE REVIEW

**Comment by jrdh** [comment]
Confirmed working in 2.9 staging environment.
